### ISSUE TITLE
Using simple syntax with Coroutine Flows

### ISSUE THREAD

**Issue by sunilson** [orbit-mvi/orbit-mvi#12]
I can't find an example in the documentation how I am supposed to use the `intent` syntax with a coroutine Flow.

For example, how would i wrap the following code:

```
    fun test() {
        job?.cancel()
        job = viewModelScope.launch { 
            testFlow.collect{
                //set state here
            }
        }
    }
```

If I understand it correctly, if I put `intent` directly after `test()`, then my `collect{}` function will always get the same state as it was when the function was first called. Do I put the intent inside the `collect{}`block?

And how would I do this with the strict syntax? (Especially the cancelling part)

Thanks!

**Comment by Rosomack** [comment]
@sunilson I can see three different questions here, so let me break it down:

- In the simple syntax, calling `state` outside of `reduce` should always yield the current MVI state

- Your solution is close, you can do something like:

```
fun test() = intent {
        job?.cancel()
        job = coroutineScope {
	          launch(Dispatchers.IO) { 
	              testFlow.collect{
					  reduce {
	                	  //set state here
					  }
	              }
	          }
		}
    }
```

Depending on what context your flow executes in, it might be a good idea to throw in `Dispatchers.XXX` to `launch` to not risk blocking the orbit "intent loop". Though this is highly dependent on your use case and might not be entirely necessary.

To simplify, if you're subscribing to one flow for the lifetime of the ViewModel there's no need to launch a new coroutine. Then it would simplify to something like:

fun test() = intent {
		withContext(Dispatchers.IO) {
			testFlow.collect{
				reduce {
					  //set state here
				}
			}
		}
    }
```

- With the "classic" strict syntax the cancelling bit is a bit more of a pain in the backside. Here's something I quickly knocked together, sorry if I didn't get it right.

```
fun requestStocks(): Unit = orbit {
        transformFlow {
            flow {
                job?.cancel()
                job = launch(Dispatchers.IO) {
                    stockRepository.stockList().collect { emit() }
                }
            }
        }.reduce {
            state.copy(stocks = event)
        }
    }
```

**Comment by mattmook** [comment]
With the simple syntax if you are using the library with Espresso the built-in idling resource won't work well with an infinite flow. You need to set `registerIdling = false` in the `intent`, so the code should be:

```
    fun requestStock(): Unit = intent(registerIdling = false) {
        stockRepository.stockDetails(itemName).collect {
            reduce {
                state.copy(stock = it)
            }
        }
    }
```

**Comment by sunilson** [comment]
Thank you for the extensive answer @Rosomack 

Great library by the way, love using it 👍

**Comment by Rosomack** [comment]
@sunilson Thanks for your kind words!
