### ISSUE TITLE
Publicly accessible state through intent extensions.

### ISSUE THREAD

**Issue by JakubMosakowski** [orbit-mvi/orbit-mvi#122]
I'm a bit worried about the idea of a public mutable state. I would assume that the state of view would be only editable inside the view model. Currently, it is open for everybody (assuming that a view model is a `ContainerHost` which is recommended) through the `intent` extension (more precisely by the `orbit` method).

I would expect that I won't be able to do smth like that: `viewModel.intent { reduce { state.copy(isLoading = true) } }` but it is allowed.

Is it implemented that way on purpose? Is it by the limitation of the interface?

**Comment by GuilhE** [comment]
@JakubMosakowski you can solve it by:
```
data class MyState(val message: String)

class MyViewModel : ViewModel() {
    private val host: ContainerHost<MyState, Nothing> = object : ContainerHost<MyState, Nothing>{
        override val container = viewModelScope.container<MyState, Nothing>(MyState())
    }

    init {
        host.intent { reduce { MyState(message = "Hello world!")} }
    }

    fun getStateFlow(): Flow<MyState> = host.container.stateFlow
    fun getSideEffectFlow(): Flow<MyState> = host.container.sideEffectFlow
}
```
