### ISSUE TITLE
Handle view diffing in XML based views.

### ISSUE THREAD

**Issue by Sardorbekcyber** [orbit-mvi/orbit-mvi#125]
Do you know any workaround to know diffing of view. In MVVM each view had its own state and rendering was appropritate to single change but when all screen is combined to single state it gets rendered on every state change. How this issue can be addressed?

I tried to use diff builder from MVI Kotlin by Ark Ivanov but there was no rendering in after navigating back.

**Comment by jakoss** [comment]
Is that really an issue for you? I was using that approach for a several years before compose and everything other than `RecyclerView` had no performance issues. Rendering pipeline is smart enough to handle that
