### ISSUE TITLE
Change container dispatcher with non-deprecated API

### ISSUE THREAD

**Issue by berhram** [orbit-mvi/orbit-mvi#141]
Current recommended way to setup container is `SettingsBuilder.()`, but I don't see how to change dispatcher with it.

**Comment by Rosomack** [comment]
@berhram we've removed the option to set the dispatcher in production code - you can only do that for tests. Setting your own dispatcher is discouraged as it may affect how orbit works (let's call it "losing the warranty" :) ).

Do you have a clear use case for this?

**Comment by berhram** [comment]
> @berhram we've removed the option to set the dispatcher in production code - you can only do that for tests. Setting your own dispatcher is discouraged as it may affect how orbit works (let's call it "losing the warranty" :) ).
> 
> Do you have a clear use case for this?

No, thanks for the comprehensive answer :)
