### ISSUE TITLE
Why SideEffect is mandatory for ContainerHost? 

### ISSUE THREAD

**Issue by yasiralijaved** [orbit-mvi/orbit-mvi#153]
I want to write a ContainerHost based ViewModel without any side effect because i don't need any side effect in a particular use case, but orbit-mvi is enforcing me to have a side effect anyway.

interface [ContainerHost](https://orbit-mvi.org/dokka/orbit-core/org.orbitmvi.orbit/-container-host/index.html)<[STATE](https://orbit-mvi.org/dokka/orbit-core/org.orbitmvi.orbit/-container-host/index.html) : [Any](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-any/index.html), [SIDE_EFFECT](https://orbit-mvi.org/dokka/orbit-core/org.orbitmvi.orbit/-container-host/index.html) : [Any](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-any/index.html)>

The question is, how can i write a ViewModel without having any side effect?

**Comment by yasiralijaved** [comment]
As an example, i want to write a CounterViewModel which just increments and decrements the count. In this case there is no need to have any side effect.

**Comment by Rosomack** [comment]
@yasiralijaved You can declare `ContainerHost<SomeState, Nothing>`
