### ISSUE TITLE
Why is NoopIdlingResource internal?

### ISSUE THREAD

**Issue by dalewking** [orbit-mvi/orbit-mvi#158]
Minor nitpick, but why isn't `NoopIdlingResource` public. I want to use dependency injection to inject an idling resource and for production it injects noop and tests can inject one that controls Espresso idling. An alternative would be to allow settings to have a null idling resource

**Comment by Rosomack** [comment]
@dalewking no specific reason - I'll look into cleaning this up

**Comment by Rosomack** [comment]
Fixed in #165
