### ISSUE TITLE
Documentation: Rename latest Release title

### ISSUE THREAD

**Issue by seljabali** [orbit-mvi/orbit-mvi#170]
Latest [release](https://github.com/orbit-mvi/orbit-mvi/releases/tag/5.0.0) has a title:
"Dependency updates, kotlin 1.8.21" 

Expected:
"5.0.0"

It should probably follow naming convention of releases as done in the [past](https://github.com/orbit-mvi/orbit-mvi/releases/).

**Comment by Rosomack** [comment]
Thanks, Done

**Comment by mattmook** [comment]
have retroactively done the same to our previous releases too :-)
