### ISSUE TITLE
Expose dependencies as they are

### ISSUE THREAD

**Issue by TWiStErRob** [orbit-mvi/orbit-mvi#177]
I'm doing an update from 4 to 6 and with the new [intent returns Job](https://github.com/orbit-mvi/orbit-mvi/releases/tag/6.0.0) change `coroutines` are now part of your public API, and therefore the dependency should be declared `api`, you can see it is `implementation` because it's listed as "Runtime" here: https://mvnrepository.com/artifact/org.orbit-mvi/orbit-core/6.0.0

Double-checked in build too:

https://github.com/orbit-mvi/orbit-mvi/blob/main/orbit-core/orbit-core_build.gradle.kts#L41

---

Out of curiosity I applied [dependency-analysis plugin](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin) (with some hacking to remove atomicfu because https://github.com/Kotlin/kotlinx-atomicfu/issues/281#issuecomment-1596833743), and it generated the following outputs:
[build-health-report.txt](https://github.com/orbit-mvi/orbit-mvi/files/11786655/build-health-report.txt)
[build-health-report.json.txt](https://github.com/orbit-mvi/orbit-mvi/files/11786657/build-health-report.json)

(It might not work with multiplatform as expected, it's geared more towards Android. For example it doesn't show what I'm reporting here 🤔.)

**Comment by TWiStErRob** [comment]
Similarly because `ViewModel.container()` has public receiver, the viewModel lib should be api (maybe not ktx, just the normal):

https://github.com/orbit-mvi/orbit-mvi/blob/main/orbit-viewmodel/orbit-viewmodel_build.gradle.kts#L36

**Comment by Rosomack** [comment]
https://github.com/orbit-mvi/orbit-mvi/releases/tag/6.1.0
