### ISSUE TITLE
How to test blockingIntent with new test framework?

### ISSUE THREAD

**Issue by TWiStErRob** [orbit-mvi/orbit-mvi#179]
Based on the documentation of `org.orbitmvi.orbit.syntax.simple.blockingIntent` it's meant for updating the state immediate like this:
```kotlin
	@OptIn(OrbitExperimental::class)
	fun update(value: Int) {
		blockingIntent {
			reduce {
				state.copy(value = value)
			}
		}
	}
```
which means I need to call
```kotlin
@Test fun test() = runTest {
	createHost().test(this) {
		expectInitialState()
		invokeIntent { update(42) }
	}
}
```
but `invokeIntent` requires `update` to return a `Job`, which `blockingIntent` doesn't.

I've also considered simply skipping `invokeIntent`, but I have no access to the `containerHost` inside the `test(this) { }` lambda.

**Comment by Rosomack** [comment]
Thanks for the report, this is an oversight. 

I'll fix it shortly - In the meantime you can return `Job()` in the `invokeIntent` lambda to make it work.

**Comment by Rosomack** [comment]
https://github.com/orbit-mvi/orbit-mvi/releases/tag/6.1.0
