### ISSUE TITLE
Give access to typed containerHost in tests through OrbitTestContext

### ISSUE THREAD

**Issue by TWiStErRob** [orbit-mvi/orbit-mvi#180]
current syntax:
```kotlin
@Test fun test() = runTest {
	createHost().test(this) {
		expectInitialState()
		invokeIntent { update(42) }
		// Need to access container host here (e.g. ViewModel) to verify some state.
	}
}
```
which means if we want access, we need:
```kotlin
@Test fun test() = runTest {
	val containerHost = createHost()
	containerHost.test(this) {
		expectInitialState()
		invokeIntent { update(42) }
		containerHost.... // is now possible
	}
}
```
but it requires change to setup code, which makes it more complicated (extra variable). It creates a captured variable in the `.test(){ }` closure and accesses that variable across coroutines as far as I see.

I propose to add this property:
```kotlin
interface OrbitTestContext {
    val containerHost: CONTAINER_HOST // impl: rename `private val actual` in RealOrbitTestContext
}
```
so we can easily access it where relevant:
```kotlin
@Test fun test() = runTest {
	createHost().test(this) {
		expectInitialState()
		invokeIntent { update(42) }
		containerHost.... // is now possible without changing test setup
	}
}
```
this becomes even more relevant when there's a convenience wrapper on top of `runTest { ... test() {` to reduce boilerplate across a large project. e.g.
```kotlin
@Test fun test() = runOrbitTest<FooViewModel> {
	expectInitialState()
	invokeIntent { update(42) }
	containerHost.... // is now possible without changing test setup
}
```
in this case one would require to set up two ways of testing depending on whether the test uses `containerHost` or not.

**Comment by mattmook** [comment]
As a temporary workaround, there's no reason you cannot write `runOrbitTest` as follows:

```
fun <CONTAINER_HOST : ContainerHost<STATE, SIDE_EFFECT>, STATE : Any, SIDE_EFFECT : Any> CONTAINER_HOST.runOrbitTest(
    block: suspend OrbitTestContext<STATE, SIDE_EFFECT, CONTAINER_HOST>.(containerHost: CONTAINER_HOST) -> Unit
) = runTest {
    this@runOrbitTest.test(this) { // optional parameters should become optional in runOrbitTest, just not writing them out here
        block(this@runOrbitTest)
    }
}
```

So then the test becomes:

```
@Test fun test() = runOrbitTest<FooViewModel> { containerHost ->
	expectInitialState()
	invokeIntent { update(42) }
	containerHost.... // is already possible without changing orbit
}
```

Of course workaround aside I can certainly see some value in exposing containerHost as suggested. However, part of me also questions the need as it sounds like you are accessing internal state of the container host which shouldn't really be public. I guess it would help to better understand your use case and what you are trying to achieve.

**Comment by TWiStErRob** [comment]
I found two use cases so far:
* Testing `blockingIntent` which doesn't return a Job. Originally I thought the only way to call a function containing blocking intent is to get a reference to containerHost, will be obsolete once #179 is fixed, workaround is to return a Job() as it was suggested.
* Simulating framework behaviour (e.g. lifecycle callbacks). Here's an example: [`ViewModel.clear()`](https://github.com/TWiStErRob/net.twisterrob.inventory/blob/19e76592c804b4e0bb5ea386577c7e7c3a44b9f7/android/space/src/test/kotlin/net/twisterrob/inventory/android/space/ManageSpaceViewModelTest.kt#L123). (Remember that the orbit `test` implicitly verifies no more state is emitted.)

I think the latter is *the* reason to have it exposed. It's not internal state per se, but more integration between orbit and other things.

**Comment by Rosomack** [comment]
I don't see a reason why we _shouldn't_ add it. After all, you already have access to the container host (external to the `test` block) in your tests.

**Comment by Rosomack** [comment]
I guess it does create a source of confusion, cause now you can run `containerHost.something()` directly instead of via `invokeIntent { }`

**Comment by Rosomack** [comment]
I really, really wish we had lambdas with multiple receivers already, then we could make `this` be both `ContainerHost` and `OrbitTestContext`... 😢 I hate this whole `invokeIntent {}` business - this is how we got to `blockingIntent` not working.

Perhaps we should just expose `containerHost`, get rid of `invokeIntent` and call it a day - it solves a host of problems and simplifies the API. Yet another breaking change though 😢

**Comment by TWiStErRob** [comment]
> Yet another breaking change though

Evolution!

> I guess it does create a source of confusion

But `invokeIntent` captures the returned `Job`, so it's not possible to "just call" an intent. I think this clarifies, also it's quite clear after seeing or writing **1** trivial test how the API works.

> now you can run containerHost.something() directly

That's what this issue is about. You're assuming that only intents and side-effects exist on the Host, but for integration there could be more methods.

> I really, really wish we had lambdas with multiple receivers already

We do: `validate: suspend context(OrbitTestContext<STATE, SIDE_EFFECT, CONTAINER_HOST>) CONTAINER_HOST.() -> Unit`

**Comment by TWiStErRob** [comment]
> both experimental and unsupported for Multiplatform

Oh, yes KMP `context` is scheduled for 2.1.

> I guess you lose the extra safety check, but I think a consistent API is more important.

I actually never opened that method :) Could that `onCreateAllowed` be handled in some other way? e.g.  reacting to `intent { }` calls inside `TestContainerDecorator`?

> The Job is passed through.

I'm confused about this, who's using it? Because I refactored all my VM to return a `Job` as I thought the testing requires it. But if I don't use it, and test don't use it, and the orbit-mvi doesn't call my functions, then it's unused.

**Comment by Rosomack** [comment]
@TWiStErRob `Jobs returned from intents serve multiple purposes:

1. You can use it in your tests to await for completion of `intents` that do not cause any emissions, but e.g. interact with external dependencies
1. They are also collected in `RealContainer` internally. At the end of a test, the test framework checks whether all in progress intents have completed (their `Job`s are complete). This is to ensure you don't have the potential for new states or side effects to arrive when you're expecting no further emissions :)

**Comment by TWiStErRob** [comment]
Ah, ok thanks! So 2) is good I would expect that from a test framework, but for that we don't need to add it to our signatures, because it happens internally. 1) is optional, and a good thing, so essentially only the `invokeIntent` signature forces us to expose the Jobs and if we had `containerHost`, we could simply remove those return types in the majority of the cases (KISS).

**Comment by Rosomack** [comment]
This is an excellent point, if we remove `invokeIntent` suddenly you are not forced to expose `Job` where you don't need it/want it.

I agree 100% @TWiStErRob we definitely intend to keep Orbit simple as it's our core philosophy :) I am definitely not satisfied with the current situation.

**Comment by Rosomack** [comment]
I will go ahead and deprecate `invokeIntent`, we can release a non-breaking change in `6.0.1` first

**Comment by TWiStErRob** [comment]
Note: without multiple receivers are we trading one evil for another? (having to repeatedly write `containerHost`)
```diff
Host().test(this) {
-    invokeIntent { someMethod() }
+    containerHost.someMethod()
}
```
the `invokeIntent` is a bit more expressive as it expresses the intent of the function call.

**Comment by Rosomack** [comment]
Fixed in https://github.com/orbit-mvi/orbit-mvi/releases/tag/6.1.0
