### ISSUE TITLE
Is it possible to add eventLoopDispatcher and intentLaunchingDispatcher to SettingsBuilder to support dispatcher configuration?

### ISSUE THREAD

**Issue by likai79511** [orbit-mvi/orbit-mvi#182]
Is it possible to add `eventLoopDispatcher` and `intentLaunchingDispatcher` to [SettingsBuilder](https://github.com/orbit-mvi/orbit-mvi/blob/9634ad42d3147bed611aaac9f32e2d21e2a97f12/orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/RealSettings.kt#L19C1-L19C31) to support dispatcher configuration?

If yes, we can control the dispatcher more flexibly. 
Such as set `TestDispatcher` to support delay-skipping in android test.

**Comment by Rosomack** [comment]
These settings are intentionally hidden. You shouldn't need to touch these to test your code effectively, including having control over virtual time.

See the [docs for guidelines](https://orbit-mvi.org/Test/new#control-over-virtual-time)

**Comment by likai79511** [comment]
@Rosomack Thanks for you reply.

If just for unit test, we can easily pass the runTest's testScope to ViewModel by `viewModel.test(scope=this)`, but it is difficult for us to use this way in androidTest.


There is a simply requirement:  when the page is initialized,  3 actions are executed:   
1. show loading
2. delay
3. hidden loading


Below is code (Jetpack Compose): 

ViewModel:

```
class MainViewModel : ContainerHost<MainState,Nothing>, ViewModel() {

    override val container: Container<MainState, Nothing> = container(MainState())

    fun initData() = intent {
        reduce { state.copy(isLoading = true) }
        delay(10_000)
        reduce { state.copy(isLoading = false) }
    }

}

data class MainState(
    val isLoading: Boolean = false
)
```

Page:
```
@Composable
fun MainPage(viewModel: MainViewModel) {

    LaunchedEffect(Unit) {
        viewModel.initData()
    }

    val state by viewModel.collectAsState()

    if (state.isLoading) {
        CircularProgressIndicator(Modifier.testTag("loading"))
    } else {
        Text(text = "content")
    }
}
```

AndroidTest will launch the Page to automatically trigger the viewModel function.
I mentioned it earlier in [Issues-175](https://github.com/orbit-mvi/orbit-mvi/issues/175), use `viewModel.container.joinIntents()` to block until all job is done, but since I don't know how to pass TestDispatcher to viewModel , it won't run on virtual time.

Test case:
```
@get:Rule
    val composeTestRule = createComposeRule()

    @Test
    fun should_display_content_when_page_init_completed() = runTest {
        val viewModel = MainViewModel()

        composeTestRule.setContent {
            MainPage(viewModel = viewModel)
        }

        composeTestRule.onNodeWithTag("loading").assertIsDisplayed()
        viewModel.container.joinIntents()
        composeTestRule.onNodeWithTag("loading").assertDoesNotExist()
        composeTestRule.onNodeWithText("content").assertIsDisplayed()
    }
```
The above test case is green, the only problem is running in real time instead of virtual time. 

Because `viewModel.test(this){}` will use `StandardTestDispatcher`(that is support delay-skipping) [TestSettings.toRealSettings](https://github.com/search?q=repo%3Aorbit-mvi%2Forbit-mvi%20TestSettings.toRealSettings&type=code#:~:text=78-,val%20dispatcher%20%3D%20testDispatcher%20%3F%3A%20StandardTestDispatcher(),-79)

I have try this way in android test, but always failed. code as bellow:
```
@Test
    fun should_display_content_when_page_init_completed2() = runTest {
        val viewModel = MainViewModel()

        composeTestRule.setContent {
            MainPage(viewModel = viewModel)
        }

        viewModel.test(this){
            composeTestRule.onNodeWithTag("loading").assertIsDisplayed()
            advanceUntilIdle() 
            composeTestRule.onNodeWithTag("loading").assertDoesNotExist()  // error thrown here
            composeTestRule.onNodeWithText("content").assertIsDisplayed()
        }
    }
```
This case failed, it seems that `advanceUntilIdle` is not waiting for all job runs to finish.

I wonder if it is possible to extend settingsBuilder to support dispatcher configuration, android test will be easy, we can pass it into viewModel.  
When I try to write a extension function for SettingsBuilder, but [settings](https://github.com/orbit-mvi/orbit-mvi/blob/09eb28fd26047c62582f790f0feb10bf6db25507/orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/RealSettings.kt#L19) is marked **internal** in SettingsBuilder...

Do you have any suggestions for this as I don't see android tests in official samples.

**Comment by Nek-12** [comment]
I was trying to benchmark Orbit for https://github.com/respawn-app/FlowMVI/issues/180, and the lack of the ability to override dispatcher forces us to either adapt to the constraints, or accept that OrbitMVI will likely have the worst performance of the compared libraries which can intentionally be optimized for high-throughput scenarios. Would love to see this reopened and dispatcher configurable.
