### ISSUE TITLE
[Question] Sealed class state, smart cast and container outdated state

### ISSUE THREAD

**Issue by franka107** [orbit-mvi/orbit-mvi#191]
Hello, thank you for this amazing library! 

I am managing my state using this sealed class:
```kotlin
sealed class ExampleState {
    object Loading : ExampleState()
    object Empty : ExampleState()
    data class Success(
        val firstName: String,
        val lastName: String,
        val age: Int
    ) : ExampleState()

    data class Error(val failure: Failure) : ExampleState()
}
```
And the declaration of my container:
```kotlin
//I could start my container with ExampleState.Empty,
// but I'll start with this state to help you understand the problem
override val container: Container<ExampleState, Nothing> =
        container(ExampleState.Success("Initial", "Initial", 0))
```

When trying to use this example intent:
```kotlin
private fun setExampleDataIntent() = intent {
    if (state is ExampleState.Success) {
        println(state.age) // <- IDE error on this line
    }
}
```
The IDE throws this error: "Smart cast to `ExampleState.Success` is impossible because `state` is a property that has an open or custom getter". However, with this code change, I managed to resolve the error:

```kotlin
private fun setExampleDataIntent() = intent {
    val uiState = state
    if (uiState is ExampleState.Success) {
        println(uiState.age) // 0
    }
}
```

But now I encountered a deeper problem. It turns out that with this implementation, the state I get from `val uiState = state` does not update after using the `reduce()` method. Take a look at the following example:

```kotlin
private fun setExampleDataIntent() = intent {
    val uiState = state
    if (uiState is ExampleState.Success) {
        println(uiState.age) // 0
        reduce { uiState.copy(
            firstName = "John",
            lastName = "Doe",
            age = 18
        ) }
        println(uiState.age) // 0 <- Error here, this should print 18
        println((state as ExampleState.Success).age) // 18
    }
}
```
This makes my solution unsafe, as the state may be outdated for the subsequent lines of code after the reduce operation. Another way to solve this problem is to cast every time I want to access the state:

```kotlin
private fun setExampleDataIntent() = intent {
    println((state as ExampleState.Success).age) // 0
    reduce {
        (state as ExampleState.Success).copy(
            firstName = "John",
            lastName = "Doe",
            age = 18
        )
    }
    println((state as ExampleState.Success).age) // 18
}
```

But, in my opinion, this would lead to verbose and redundant code. So what solution could you apply to this problem? How can I access my state if its type is `ExampleState.Success` and always get its updated value?

**Comment by Rosomack** [comment]
> The IDE throws this error: "Smart cast to ExampleState.Success is impossible because state is a property that has an open or custom getter". However, with this code change, I managed to resolve the error:

I'm not sure we can do anything about it. `state` is a volatile property - the current state of the container is captured at the point of calling it. Every time you read it it could be different - so the IDE is rightly saying the smart cast is impossible as it could result in a runtime crash. 

Still, I captured this on our board #191.

> But now I encountered a deeper problem. It turns out that with this implementation, the state I get from val uiState = state does not update after using the reduce() method. Take a look at the following example:

This is as designed - Orbit does not mutate the state, it produces a new one every time you reduce. Mutable state is a frequent source of bugs, which is why we avoid it.

When you capture the state into a `val` it should never change (as long as your state class is immutable).

---

Now when it comes to handling sealed class states it's a deeper topic. I have to admit I haven't really found a solution to this myself - not that I tried hard to find it.

A quick fix could be to introduce an extension function that hides this cast for you e.g.

```kotlin
private fun SimpleContext<ExampleState>.expectSuccessState() = state as ExampleState.Success
private fun SimpleSyntax<ExampleState, ExampleEvent>.expectSuccessState() =  state as ExampleState.Success
```


Some random thoughts of how we could help by adding new DSL methods
```kotlin
private fun setExampleDataIntent() = intentForState<ExampleState.Success> {
    reduce {
        state.copy(
            firstName = "John",
            lastName = "Doe",
            age = 18
        )
    }
    println(state.age) // 18
}

OR

private fun setExampleDataIntent() = intent {

    withSubstate<ExampleState.Success>(throwOnMismatch=true) {
         reduce {
             state.copy(
                  firstName = "John",
                  lastName = "Doe",
                  age = 18
             )
        }
    }
}
````

**Comment by jadar** [comment]
The way I've dealt with this is by using the elvis operator...

```
intent {
    val success = state as? ExampleState.Success
        ?: return@intent
    // use success as your state variable.
}
```

This way you also work around any volatile property issues.

**Comment by Rosomack** [comment]
Solved in https://github.com/orbit-mvi/orbit-mvi/pull/214
