### ISSUE TITLE
Create multiplatform sample

### ISSUE THREAD

**Issue by Rosomack** [orbit-mvi/orbit-mvi#20]
iOS support right now is bare-bones. We need to create a proper multiplatform app sample in order to create cross-platform solutions to:

1. State saving
2. ViewModel equivalent
3. Combine framework wrapper

**Comment by kenyee** [comment]
linking this repo in case anyone else is looking for it:
https://github.com/orbit-mvi/orbit-sample-posts-multiplatform

I didn't see how iOS does state restoration in that sample but using Moko viewmodels looks very clean.
