### ISSUE TITLE
StateFlow support in the Container

### ISSUE THREAD

**Issue by raviteja786143** [orbit-mvi/orbit-mvi#35]
Can we change the `public val stateFlow: Flow<STATE> ` in the Container to  `public val stateFlow: StateFlow<STATE>`. 

While initializing the container in ViewModel, we will be setting up the initial state. In Jetpack compose while consuming this, we can get the initial state from (Mutable)StateFlow and collectAsState()

```
@Composable
fun SomeCompose(viewModel: SomeViewModel){

    val someState = viewModel.container.stateFlow.collectAsState(initial = [initialState]) 

    // will be changed to

    val someState = viewModel.container.stateFlow.collectAsState() 
    
}

```

we can get initial state from (Mutable)StateFlow and collectAsState()

**Comment by Rosomack** [comment]
Fixed in #38.
