### ISSUE TITLE
Update sideEffectFlow collection recommendations

### ISSUE THREAD

**Issue by Rosomack** [orbit-mvi/orbit-mvi#42]
Thanks for the report @mochadwi.

`launchWhenX` methods in Android drop events received when the lifecycle suspends the collecting coroutine and then it gets destroyed over a configuration change. [Thread](https://gist.github.com/gmk57/330a7d214f5d710811c6b5ce27ceedaa). This is a corner case, but could lead to some potentially important events being dropped.

There's nothing we can do in core Orbit to prevent it. We need to update our samples and documentation to use new Google APIs that do not suffer from this problem as per [this article](https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda).

**Comment by mattmook** [comment]
@Rosomack do we have a preferred implementation?

The options are either, 1:

```
lifecycleScope.launch {        
    lifecycle.repeatOnLifecycle(Lifecycle.State.RESUMED) {
        viewModel.container.sideEffectFlow.collect { handleSideEffect(it) }
    }
}
```

or 2:

```
lifecycleScope.launch {
    viewModel.container.sideEffectFlow.flowWithLifecycle(this, Lifecycle.State.STARTED).collect { handleSideEffect(it) }
}
```

I personally prefer 2. It's worth noting that it is recommended to use `flowWithLifecycle` with Jetpack Compose.

**Comment by Rosomack** [comment]
Yeah agreed, 2 seems nicer.

**Comment by behzod1996** [comment]
I would prefer this implementation:

```
viewModel.container.sideEffectFlow
                                .flowWithLifecycle(lifecycle)
                                .onEach { handleEffect(it)}
                                .launchIn(lifecycleScope)
```
