### ISSUE TITLE
Warnings on all simple syntax DSL methods

### ISSUE THREAD

**Issue by sunilson** [orbit-mvi/orbit-mvi#46]
At the moment all my simple syntax DSL methods like `reduce` and `postSideEffect` are marked with a red line with the following warning:

![image](https://user-images.githubusercontent.com/8208775/122713441-fd695280-d265-11eb-84dc-73ee6dc7d6b7.png)

Is this a known issue and can I do something about that? It compiles and runs just fine, but all the warnings are triggering me 😂

**Comment by mattmook** [comment]
Can you show some more of the code? This should only happen if you nest things that shouldn't be nested.

**Comment by sunilson** [comment]
Here is an example:

![image](https://user-images.githubusercontent.com/8208775/123054799-866ac000-d405-11eb-973d-d3276fa36bad.png)

I am using Android Studio 4.2.1

**Comment by Rosomack** [comment]
> Here is an example:
> 
> ![image](https://user-images.githubusercontent.com/8208775/123054799-866ac000-d405-11eb-973d-d3276fa36bad.png)
> 
> I am using Android Studio 4.2.1

@sunilson what version of Kotlin are you on? This issue seems pretty odd.

**Comment by sunilson** [comment]
1.3.72

After updating to 1.5.10 the error disappears, so I guess that's the problem. Gonna have to update our project :) Thanks and sorry for taking up your time, could have thought about that myself 😅

**Comment by mattmook** [comment]
No worries @sunilson, glad it fixed the issue
