### ISSUE TITLE
How to use suspend room fuction in viewmodel intent?

### ISSUE THREAD

**Issue by avvensis** [orbit-mvi/orbit-mvi#77]
In my test ViewModel

```kotlin

    private val _testFlow = MutableStateFlow(0)
    val testFlow: StateFlow<Int> = _testFlow.asStateFlow()

    fun testFlow() {
        viewModelScope.launch {
            val values = repository.getAllItems()
            _testFlow.emit(values.count())
        }
    }

    fun testIntent() = intent() {
        reduce { state.copyToLoading() }
        val values = repository.getAllItems()
        reduce {
            state.copyToSuccess(values)
        }
    }
```

DAO looks like

```kotlin
@Dao
interface TestDao {
  @Query("SOME SQL WITH INNER JOIN")
  suspend fun getAllItems(): List<TestView>
}
```

in first case with ```testFlow``` repository.getAllItems returns 3 records from the Room, but second case with ```testIntent``` returns 0 records. 

It's look like i incorrect use intents with suspend functions. Could you help me?

**Comment by ntoskrnl** [comment]
Is it the exact code that you run?
In the example the you provided, `fun testIntent()` missing  the line `_testFlow.emit(values.count())`.

**Comment by avvensis** [comment]
Nope it's adopted and simplified version of code.
Both version created to check that ```repository.getallitems``` works. And result was checked in logcat observers at fragment.

If you don't see the problem in the code at first look, should i create some demo project to check it together?

**Comment by avvensis** [comment]
It's my mistake.

I used in memory database for development with a lot of data from assets jsons that was inserted by chunks. 
So fetching calls before the data was inserted.

It's good example of async hell!

I'm sorry and thanks for your attention.
