### ISSUE TITLE
"orbit-posts" sample project is slow for first seconds after opening

### ISSUE THREAD

**Issue by MaciejG** [orbit-mvi/orbit-mvi#85]
**orbit-posts** (https://github.com/orbit-mvi/orbit-mvi/tree/main/samples/orbit-posts) example project skips frames and is very unresponsive for first couple of seconds. The list of Posts is hardly usable for those first seconds. This is reproduceable on emulator and physical devices. 

Clearly main thread is occupied with something. I checked **orbit-sample-stocklist-jetpack-compose** (https://github.com/orbit-mvi/orbit-sample-stocklist-jetpack-compose) example project and nothing like it happens there. I tried to find out if images (avatarUrl field in Post) are responsible for that, but the application is still slow even after removing images completely from the list.

I also switched the whole project to **Hilt**. No luck. Still slow.

I build very similar example project based on MVIKotlin library and it was much faster. But horribly bloated when it comes to code. Please fix the performance of the sample project so that we could see how to write apps with your lib.

**Comment by mattmook** [comment]
Indeed having looked at the problem in more detail, this was really an issue of embedding a RecyclerView in a NestedScrollView so all 100 rows of the RecyclerView were inflating when the data came in. Oops. PR is in place to fix this.
