### ISSUE TITLE
Sponsorship / Donations

### ISSUE THREAD

**Issue by GuilhE** [orbit-mvi/orbit-mvi#94]
Hello,
The company I work for is organizing a donation wave to support projects/teams that are doing a tremendous job helping out the open source community. Orbit-Mvi it's one of these, no doubt.

I've talked already with @mattmook on slack, but I'll leave this "issue" open to better track it's progress.

Are you open for donations/sponsorship?

Regards

**Comment by GuilhE** [comment]
Any update? @mattmook @Rosomack

**Comment by mattmook** [comment]
For a status update, everything has been submitted to GitHub but currently awaiting approval.

**Comment by mattmook** [comment]
Just been approved, so PR awaiting @Rosomack approval for the link to become active.

**Comment by GuilhE** [comment]
Hello, 

The donation was made! 🎊 

We want to create a wave of support that can grow as it moves forward in time, allowing companies and individuals to participate within their scale and possibilities. And that’s why we’ve created the [Open Source Donation Wave](https://opensourcedonationwave.com/).
Please feel free to share it to hopefully widen the range of this initiative and start a movement that could create a ripple donation effect 😃.

Best regards, and thank you for Orbit-Mvi once again.
