### ISSUE TITLE
Side effects are not cached if there are no observers.

### ISSUE THREAD

**Issue by DupinC** [orbit-mvi/orbit-mvi#95]
Hi ! The Orbit documentation said that [Side effects are cached if there are no observers, guaranteeing critical events such as navigation are delivered after re-subscription.](https://orbit-mvi.org/Core/overview#:~:text=Side%20effects%20are%20cached%20if%20there%20are%20no%20observers%2C%20guaranteeing%20critical%20events%20such%20as%20navigation%20are%20delivered%20after%20re%2Dsubscription.)

But with this sample : 

```
class MainActivity : ComponentActivity() {

    private val buttonViewModel: ButtonViewModel by viewModels()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            ButtonToClick(buttonViewModel, ::handleSideEffect)
        }
    }

    private fun handleSideEffect(sideEffect: ButtonSideEffect) {
        when (sideEffect) {
            is ButtonSideEffect -> Toast.makeText(this, sideEffect.message, Toast.LENGTH_LONG).show()
        }
    }
}

sealed class ButtonState
object IdleState: ButtonState()
object ClickedState: ButtonState()

data class ButtonSideEffect(val message: String)

@Composable
fun ButtonToClick(buttonViewModel: ButtonViewModel, handleSideEffect: (ButtonSideEffect) -> Unit = {}) {
    val buttonState = buttonViewModel.container.stateFlow.collectAsState().value

    LaunchedEffect(buttonViewModel) {
        launch {
            buttonViewModel.container.sideEffectFlow.collect { sideEffect ->
                handleSideEffect(sideEffect)
            }
        }
    }

    Button(onClick = { buttonViewModel.onButtonClicked() }, enabled = buttonState is IdleState){
        Text(text = "Click me")
    }
}

class ButtonViewModel: ViewModel(), ContainerHost<ButtonState, ButtonSideEffect> {
    override val container: Container<ButtonState, ButtonSideEffect> = container(IdleState){
        intent { reduce { IdleState } }
    }

    fun onButtonClicked() = intent {
        reduce { ClickedState }

        delay(5000)
        postSideEffect(ButtonSideEffect("Button clicked"))

        reduce { IdleState }
    }
}
```

When I :
1. Click the button
2. Turn off my phone screen
3. Wait for 5 second 
4. Turn it back on

the Toast doesn't appear.

In my "real world" scenario the SideEffect is a navigation event happening on a loading screen. The loading take a while and if the user put is phone aside and come back later, he's stuck on the loading screen.

Am I doing someting wrong with the collection of the side effects ?

**Comment by DupinC** [comment]
I think I figured it out :

Instead of collecting the sideEffectFlow with a simple "launch", I collected it this way :

```
val lifecycleOwner = LocalLifecycleOwner.current

LaunchedEffect(Unit) {
    lifecycleOwner.lifecycle.repeatOnLifecycle(Lifecycle.State.STARTED){
        buttonViewModel.container.sideEffectFlow.collect { sideEffect ->
            handleSideEffect(sideEffect)
        }
    }
}
```

Does that seems ok to you ?

**Comment by mattmook** [comment]
Hi @DupinC thanks for the report, I will check this out soon. We're doing the same in our orbit-compose module as your original code so we'd want to update that too.

**Comment by mattmook** [comment]
hi @DupinC, if I understand Compose correctly (???), I believe your code above is most of the way there.

The only thing I've noted is `LaunchedEffect` should be keyed, I'd assume off the flow and lifecycle owner, in a similar way to the state flow example in [Safe Flow collection in Jetpack Compose](https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda#27a9). If you look at the code for `LaunchedEffect` you'll see it basically does a `remember` on those keyed values, hence why `Unit` would not be correct.

So I'm thinking something like the code below, which should then live in [observe.kt](https://github.com/orbit-mvi/orbit-mvi/blob/main/orbit-compose/src/main/kotlin/org/orbitmvi/orbit/compose/observe.kt):

```
@Composable
public fun <STATE : Any, SIDE_EFFECT : Any> ContainerHost<STATE, SIDE_EFFECT>.collectSideEffect(
    sideEffect: (suspend (sideEffect: SIDE_EFFECT) -> Unit)
) {
    val sideEffectFlow = container.sideEffectFlow
    val lifecycleOwner = LocalLifecycleOwner.current

    LaunchedEffect(sideEffectFlow, lifecycleOwner) {
        lifecycleOwner.lifecycle.repeatOnLifecycle(Lifecycle.State.STARTED) {
            sideEffectFlow.collect { sideEffect(it) }
        }
    }
}
```

I need to do a little more testing on the above code before I create a PR to the project so this is more just a heads up.

**Comment by DupinC** [comment]
Thanks for the heads up !

Sounds good to me (even if I'm a compose beginner 😅 )
